name: main

env:
  LANG: C.UTF-8

on:
  pull_request:
  push:
    branches:
    - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    name: build and deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
      - name: build dependencies
        run: cabal build --only-dependencies
      - name: build
        run: cabal build
      - name: run
        run: cabal run cocktails -- --start-db
      - name: deploy gh pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
